// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Abelian.proto

package xyz.securegram.axolotl;

public final class AbelianProtos {
  private AbelianProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AbelianIdentityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:securegram.AbelianIdentity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 deviceId = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional uint32 deviceId = 1;</code>
     */
    int getDeviceId();

    /**
     * <code>optional bytes identityKey = 2;</code>
     */
    boolean hasIdentityKey();
    /**
     * <code>optional bytes identityKey = 2;</code>
     */
    com.google.protobuf.ByteString getIdentityKey();

    /**
     * <code>optional bytes signedPreKey = 3;</code>
     */
    boolean hasSignedPreKey();
    /**
     * <code>optional bytes signedPreKey = 3;</code>
     */
    com.google.protobuf.ByteString getSignedPreKey();

    /**
     * <code>optional bytes signedPreKeySignature = 4;</code>
     */
    boolean hasSignedPreKeySignature();
    /**
     * <code>optional bytes signedPreKeySignature = 4;</code>
     */
    com.google.protobuf.ByteString getSignedPreKeySignature();
  }
  /**
   * Protobuf type {@code securegram.AbelianIdentity}
   */
  public static final class AbelianIdentity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:securegram.AbelianIdentity)
      AbelianIdentityOrBuilder {
    // Use AbelianIdentity.newBuilder() to construct.
    private AbelianIdentity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AbelianIdentity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AbelianIdentity defaultInstance;
    public static AbelianIdentity getDefaultInstance() {
      return defaultInstance;
    }

    public AbelianIdentity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AbelianIdentity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              identityKey_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              signedPreKey_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              signedPreKeySignature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianIdentity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianIdentity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.securegram.axolotl.AbelianProtos.AbelianIdentity.class, xyz.securegram.axolotl.AbelianProtos.AbelianIdentity.Builder.class);
    }

    public static com.google.protobuf.Parser<AbelianIdentity> PARSER =
        new com.google.protobuf.AbstractParser<AbelianIdentity>() {
      public AbelianIdentity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AbelianIdentity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AbelianIdentity> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private int deviceId_;
    /**
     * <code>optional uint32 deviceId = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 deviceId = 1;</code>
     */
    public int getDeviceId() {
      return deviceId_;
    }

    public static final int IDENTITYKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString identityKey_;
    /**
     * <code>optional bytes identityKey = 2;</code>
     */
    public boolean hasIdentityKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes identityKey = 2;</code>
     */
    public com.google.protobuf.ByteString getIdentityKey() {
      return identityKey_;
    }

    public static final int SIGNEDPREKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString signedPreKey_;
    /**
     * <code>optional bytes signedPreKey = 3;</code>
     */
    public boolean hasSignedPreKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes signedPreKey = 3;</code>
     */
    public com.google.protobuf.ByteString getSignedPreKey() {
      return signedPreKey_;
    }

    public static final int SIGNEDPREKEYSIGNATURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString signedPreKeySignature_;
    /**
     * <code>optional bytes signedPreKeySignature = 4;</code>
     */
    public boolean hasSignedPreKeySignature() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes signedPreKeySignature = 4;</code>
     */
    public com.google.protobuf.ByteString getSignedPreKeySignature() {
      return signedPreKeySignature_;
    }

    private void initFields() {
      deviceId_ = 0;
      identityKey_ = com.google.protobuf.ByteString.EMPTY;
      signedPreKey_ = com.google.protobuf.ByteString.EMPTY;
      signedPreKeySignature_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, identityKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, signedPreKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, signedPreKeySignature_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, identityKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, signedPreKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, signedPreKeySignature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xyz.securegram.axolotl.AbelianProtos.AbelianIdentity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code securegram.AbelianIdentity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:securegram.AbelianIdentity)
        xyz.securegram.axolotl.AbelianProtos.AbelianIdentityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianIdentity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianIdentity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.securegram.axolotl.AbelianProtos.AbelianIdentity.class, xyz.securegram.axolotl.AbelianProtos.AbelianIdentity.Builder.class);
      }

      // Construct using xyz.securegram.axolotl.AbelianProtos.AbelianIdentity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        identityKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        signedPreKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        signedPreKeySignature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianIdentity_descriptor;
      }

      public xyz.securegram.axolotl.AbelianProtos.AbelianIdentity getDefaultInstanceForType() {
        return xyz.securegram.axolotl.AbelianProtos.AbelianIdentity.getDefaultInstance();
      }

      public xyz.securegram.axolotl.AbelianProtos.AbelianIdentity build() {
        xyz.securegram.axolotl.AbelianProtos.AbelianIdentity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xyz.securegram.axolotl.AbelianProtos.AbelianIdentity buildPartial() {
        xyz.securegram.axolotl.AbelianProtos.AbelianIdentity result = new xyz.securegram.axolotl.AbelianProtos.AbelianIdentity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.identityKey_ = identityKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.signedPreKey_ = signedPreKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.signedPreKeySignature_ = signedPreKeySignature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.securegram.axolotl.AbelianProtos.AbelianIdentity) {
          return mergeFrom((xyz.securegram.axolotl.AbelianProtos.AbelianIdentity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.securegram.axolotl.AbelianProtos.AbelianIdentity other) {
        if (other == xyz.securegram.axolotl.AbelianProtos.AbelianIdentity.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasIdentityKey()) {
          setIdentityKey(other.getIdentityKey());
        }
        if (other.hasSignedPreKey()) {
          setSignedPreKey(other.getSignedPreKey());
        }
        if (other.hasSignedPreKeySignature()) {
          setSignedPreKeySignature(other.getSignedPreKeySignature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xyz.securegram.axolotl.AbelianProtos.AbelianIdentity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xyz.securegram.axolotl.AbelianProtos.AbelianIdentity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int deviceId_ ;
      /**
       * <code>optional uint32 deviceId = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 deviceId = 1;</code>
       */
      public int getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>optional uint32 deviceId = 1;</code>
       */
      public Builder setDeviceId(int value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 deviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString identityKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes identityKey = 2;</code>
       */
      public boolean hasIdentityKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes identityKey = 2;</code>
       */
      public com.google.protobuf.ByteString getIdentityKey() {
        return identityKey_;
      }
      /**
       * <code>optional bytes identityKey = 2;</code>
       */
      public Builder setIdentityKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        identityKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes identityKey = 2;</code>
       */
      public Builder clearIdentityKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        identityKey_ = getDefaultInstance().getIdentityKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signedPreKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signedPreKey = 3;</code>
       */
      public boolean hasSignedPreKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes signedPreKey = 3;</code>
       */
      public com.google.protobuf.ByteString getSignedPreKey() {
        return signedPreKey_;
      }
      /**
       * <code>optional bytes signedPreKey = 3;</code>
       */
      public Builder setSignedPreKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        signedPreKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signedPreKey = 3;</code>
       */
      public Builder clearSignedPreKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        signedPreKey_ = getDefaultInstance().getSignedPreKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signedPreKeySignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signedPreKeySignature = 4;</code>
       */
      public boolean hasSignedPreKeySignature() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes signedPreKeySignature = 4;</code>
       */
      public com.google.protobuf.ByteString getSignedPreKeySignature() {
        return signedPreKeySignature_;
      }
      /**
       * <code>optional bytes signedPreKeySignature = 4;</code>
       */
      public Builder setSignedPreKeySignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        signedPreKeySignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signedPreKeySignature = 4;</code>
       */
      public Builder clearSignedPreKeySignature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        signedPreKeySignature_ = getDefaultInstance().getSignedPreKeySignature();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:securegram.AbelianIdentity)
    }

    static {
      defaultInstance = new AbelianIdentity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:securegram.AbelianIdentity)
  }

  public interface AbelianEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:securegram.AbelianEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .securegram.AbelianEnvelope.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .securegram.AbelianEnvelope.Type type = 1;</code>
     */
    xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type getType();

    /**
     * <code>optional bytes content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code securegram.AbelianEnvelope}
   */
  public static final class AbelianEnvelope extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:securegram.AbelianEnvelope)
      AbelianEnvelopeOrBuilder {
    // Use AbelianEnvelope.newBuilder() to construct.
    private AbelianEnvelope(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AbelianEnvelope(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AbelianEnvelope defaultInstance;
    public static AbelianEnvelope getDefaultInstance() {
      return defaultInstance;
    }

    public AbelianEnvelope getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AbelianEnvelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type value = xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianEnvelope_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.class, xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Builder.class);
    }

    public static com.google.protobuf.Parser<AbelianEnvelope> PARSER =
        new com.google.protobuf.AbstractParser<AbelianEnvelope>() {
      public AbelianEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AbelianEnvelope(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AbelianEnvelope> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code securegram.AbelianEnvelope.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0, 0),
      /**
       * <code>CIPHERTEXT = 1;</code>
       */
      CIPHERTEXT(1, 1),
      /**
       * <code>KEY_EXCHANGE = 2;</code>
       */
      KEY_EXCHANGE(2, 2),
      /**
       * <code>PREKEY_BUNDLE = 3;</code>
       */
      PREKEY_BUNDLE(3, 3),
      /**
       * <code>RECEIPT = 5;</code>
       */
      RECEIPT(4, 5),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>CIPHERTEXT = 1;</code>
       */
      public static final int CIPHERTEXT_VALUE = 1;
      /**
       * <code>KEY_EXCHANGE = 2;</code>
       */
      public static final int KEY_EXCHANGE_VALUE = 2;
      /**
       * <code>PREKEY_BUNDLE = 3;</code>
       */
      public static final int PREKEY_BUNDLE_VALUE = 3;
      /**
       * <code>RECEIPT = 5;</code>
       */
      public static final int RECEIPT_VALUE = 5;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return CIPHERTEXT;
          case 2: return KEY_EXCHANGE;
          case 3: return PREKEY_BUNDLE;
          case 5: return RECEIPT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:securegram.AbelianEnvelope.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type type_;
    /**
     * <code>optional .securegram.AbelianEnvelope.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .securegram.AbelianEnvelope.Type type = 1;</code>
     */
    public xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type getType() {
      return type_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      type_ = xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type.UNKNOWN;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code securegram.AbelianEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:securegram.AbelianEnvelope)
        xyz.securegram.axolotl.AbelianProtos.AbelianEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianEnvelope_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.class, xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Builder.class);
      }

      // Construct using xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.securegram.axolotl.AbelianProtos.internal_static_securegram_AbelianEnvelope_descriptor;
      }

      public xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope getDefaultInstanceForType() {
        return xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.getDefaultInstance();
      }

      public xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope build() {
        xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope buildPartial() {
        xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope result = new xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope) {
          return mergeFrom((xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope other) {
        if (other == xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type type_ = xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type.UNKNOWN;
      /**
       * <code>optional .securegram.AbelianEnvelope.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .securegram.AbelianEnvelope.Type type = 1;</code>
       */
      public xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type getType() {
        return type_;
      }
      /**
       * <code>optional .securegram.AbelianEnvelope.Type type = 1;</code>
       */
      public Builder setType(xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .securegram.AbelianEnvelope.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = xyz.securegram.axolotl.AbelianProtos.AbelianEnvelope.Type.UNKNOWN;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:securegram.AbelianEnvelope)
    }

    static {
      defaultInstance = new AbelianEnvelope(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:securegram.AbelianEnvelope)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securegram_AbelianIdentity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_securegram_AbelianIdentity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_securegram_AbelianEnvelope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_securegram_AbelianEnvelope_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rAbelian.proto\022\nsecuregram\"m\n\017AbelianId" +
      "entity\022\020\n\010deviceId\030\001 \001(\r\022\023\n\013identityKey\030" +
      "\002 \001(\014\022\024\n\014signedPreKey\030\003 \001(\014\022\035\n\025signedPre" +
      "KeySignature\030\004 \001(\014\"\251\001\n\017AbelianEnvelope\022." +
      "\n\004type\030\001 \001(\0162 .securegram.AbelianEnvelop" +
      "e.Type\022\017\n\007content\030\002 \001(\014\"U\n\004Type\022\013\n\007UNKNO" +
      "WN\020\000\022\016\n\nCIPHERTEXT\020\001\022\020\n\014KEY_EXCHANGE\020\002\022\021" +
      "\n\rPREKEY_BUNDLE\020\003\022\013\n\007RECEIPT\020\005B\'\n\026xyz.se" +
      "curegram.axolotlB\rAbelianProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_securegram_AbelianIdentity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_securegram_AbelianIdentity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_securegram_AbelianIdentity_descriptor,
        new java.lang.String[] { "DeviceId", "IdentityKey", "SignedPreKey", "SignedPreKeySignature", });
    internal_static_securegram_AbelianEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_securegram_AbelianEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_securegram_AbelianEnvelope_descriptor,
        new java.lang.String[] { "Type", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
